version: "3"

services:
  dnscrypt-proxy:
    image: gists/dnscrypt-proxy
    ports:
        - "PIHOLE_DNS_PORT:5353/udp"
        - "PIHOLE_DNS_PORT:5353/tcp"
    volumes:
        - 'DNSCRYPT_MACRO'
    restart: always
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
      - "80:80/tcp"
    environment:
      TZ: 'America/Chicago'
      WEBPASSWORD: 'PASS_MACRO'
      PIHOLE_DNS_: 'PIHOLEDNS' 
    volumes:
      - 'ETC_MACRO'
      - 'DNS_MACRO'
    cap_add:
      - NET_ADMIN
    restart: unless-stopped
