install_tools:
	sudo apt-get install -y libffi-dev libssl-dev
	sudo apt-get install -y python3 python3-pip
	sudo apt-get remove python-configparser
	sudo apt-get install -y vim git

install_python_packages:
	sudo pip3 -v install requirements.txt
	
